#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-filehash
Version  : 2.4.1
Release  : 3
URL      : https://cran.r-project.org/src/contrib/filehash_2.4-1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/filehash_2.4-1.tar.gz
Summary  : Simple Key-Value Database
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-filehash-lib
BuildRequires : clr-R-helpers

%description
are associated with data values that are stored on the disk. A simple interface is provided for inserting,
  retrieving, and deleting data from the database. Utilities are provided that allow 'filehash' databases to be
  treated much like environments and lists are already used in R. These utilities are provided to encourage
  interactive and exploratory analysis on large datasets. Three different file formats for representing the
  database are currently available and new formats can easily be incorporated by third parties for use in the
  'filehash' framework.

%package lib
Summary: lib components for the R-filehash package.
Group: Libraries

%description lib
lib components for the R-filehash package.


%prep
%setup -q -c -n filehash

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1530336359

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1530336359
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library filehash
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library filehash
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library filehash
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library filehash|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/filehash/CITATION
/usr/lib64/R/library/filehash/COPYING
/usr/lib64/R/library/filehash/DESCRIPTION
/usr/lib64/R/library/filehash/INDEX
/usr/lib64/R/library/filehash/Meta/Rd.rds
/usr/lib64/R/library/filehash/Meta/features.rds
/usr/lib64/R/library/filehash/Meta/hsearch.rds
/usr/lib64/R/library/filehash/Meta/links.rds
/usr/lib64/R/library/filehash/Meta/nsInfo.rds
/usr/lib64/R/library/filehash/Meta/package.rds
/usr/lib64/R/library/filehash/Meta/vignette.rds
/usr/lib64/R/library/filehash/NAMESPACE
/usr/lib64/R/library/filehash/NEWS
/usr/lib64/R/library/filehash/R/filehash
/usr/lib64/R/library/filehash/R/filehash.rdb
/usr/lib64/R/library/filehash/R/filehash.rdx
/usr/lib64/R/library/filehash/doc/filehash.R
/usr/lib64/R/library/filehash/doc/filehash.Rnw
/usr/lib64/R/library/filehash/doc/filehash.pdf
/usr/lib64/R/library/filehash/doc/index.html
/usr/lib64/R/library/filehash/help/AnIndex
/usr/lib64/R/library/filehash/help/aliases.rds
/usr/lib64/R/library/filehash/help/filehash.rdb
/usr/lib64/R/library/filehash/help/filehash.rdx
/usr/lib64/R/library/filehash/help/paths.rds
/usr/lib64/R/library/filehash/html/00Index.html
/usr/lib64/R/library/filehash/html/R.css
/usr/lib64/R/library/filehash/libs/symbols.rds

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/filehash/libs/filehash.so
/usr/lib64/R/library/filehash/libs/filehash.so.avx2
/usr/lib64/R/library/filehash/libs/filehash.so.avx512
