#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v12
# autospec commit: a5d3013
#
Name     : R-filehash
Version  : 2.4.6
Release  : 47
URL      : https://cran.r-project.org/src/contrib/filehash_2.4-6.tar.gz
Source0  : https://cran.r-project.org/src/contrib/filehash_2.4-6.tar.gz
Summary  : Simple Key-Value Database
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: R-filehash-lib = %{version}-%{release}
Requires: R-filehash-license = %{version}-%{release}
Requires: R-digest
BuildRequires : R-digest
BuildRequires : buildreq-R

%description
are associated with data values that are stored on the disk. A simple interface is provided for inserting,
  retrieving, and deleting data from the database. Utilities are provided that allow 'filehash' databases to be
  treated much like environments and lists are already used in R. These utilities are provided to encourage
  interactive and exploratory analysis on large datasets. Three different file formats for representing the
  database are currently available and new formats can easily be incorporated by third parties for use in the
  'filehash' framework.

%package lib
Summary: lib components for the R-filehash package.
Group: Libraries
Requires: R-filehash-license = %{version}-%{release}

%description lib
lib components for the R-filehash package.


%package license
Summary: license components for the R-filehash package.
Group: Default

%description license
license components for the R-filehash package.


%prep
%setup -q -n filehash
pushd ..
cp -a filehash buildavx2
popd
pushd ..
cp -a filehash buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1719420050

%install
export SOURCE_DATE_EPOCH=1719420050
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-filehash
cp %{_builddir}/filehash/inst/COPYING %{buildroot}/usr/share/package-licenses/R-filehash/05cde7f3cd671233778c15c96fc8c47d06216577 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/filehash/CITATION
/usr/lib64/R/library/filehash/COPYING
/usr/lib64/R/library/filehash/DESCRIPTION
/usr/lib64/R/library/filehash/INDEX
/usr/lib64/R/library/filehash/Meta/Rd.rds
/usr/lib64/R/library/filehash/Meta/features.rds
/usr/lib64/R/library/filehash/Meta/hsearch.rds
/usr/lib64/R/library/filehash/Meta/links.rds
/usr/lib64/R/library/filehash/Meta/nsInfo.rds
/usr/lib64/R/library/filehash/Meta/package.rds
/usr/lib64/R/library/filehash/Meta/vignette.rds
/usr/lib64/R/library/filehash/NAMESPACE
/usr/lib64/R/library/filehash/NEWS
/usr/lib64/R/library/filehash/R/filehash
/usr/lib64/R/library/filehash/R/filehash.rdb
/usr/lib64/R/library/filehash/R/filehash.rdx
/usr/lib64/R/library/filehash/doc/filehash.R
/usr/lib64/R/library/filehash/doc/filehash.Rnw
/usr/lib64/R/library/filehash/doc/filehash.pdf
/usr/lib64/R/library/filehash/doc/index.html
/usr/lib64/R/library/filehash/help/AnIndex
/usr/lib64/R/library/filehash/help/aliases.rds
/usr/lib64/R/library/filehash/help/filehash.rdb
/usr/lib64/R/library/filehash/help/filehash.rdx
/usr/lib64/R/library/filehash/help/paths.rds
/usr/lib64/R/library/filehash/html/00Index.html
/usr/lib64/R/library/filehash/html/R.css
/usr/lib64/R/library/filehash/tests/SHA1SUM
/usr/lib64/R/library/filehash/tests/digest.R
/usr/lib64/R/library/filehash/tests/digest.Rout.save
/usr/lib64/R/library/filehash/tests/misc/create-testdb.R
/usr/lib64/R/library/filehash/tests/reg-tests.R
/usr/lib64/R/library/filehash/tests/reg-tests.Rout.save
/usr/lib64/R/library/filehash/tests/testdb-v1.1
/usr/lib64/R/library/filehash/tests/testdb-v2.0
/usr/lib64/R/library/filehash/tests/versions.R
/usr/lib64/R/library/filehash/tests/versions.Rout.save

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/filehash/libs/filehash.so
/V4/usr/lib64/R/library/filehash/libs/filehash.so
/usr/lib64/R/library/filehash/libs/filehash.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-filehash/05cde7f3cd671233778c15c96fc8c47d06216577
